DROP TABLE IF EXISTS Kayttaja CASCADE;

DROP TABLE IF EXISTS Tehtava CASCADE;

DROP TABLE IF EXISTS Luokka CASCADE;

DROP TABLE IF EXISTS Tarkeys CASCADE;

DROP TABLE IF EXISTS TehtavaLuokka CASCADE;
